# Generated by Django 5.0.1 on 2024-01-27 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('squats', 'Squats'), ('bicep_curl', 'Bicep Curl')], max_length=20)),
                ('rep_count', models.IntegerField()),
                ('time_limit_seconds', models.IntegerField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.routine')),
            ],
        ),
    ]
