# Generated by Django 5.0.1 on 2024-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_workout_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.CharField(choices=[('squats', 'Squats'), ('bicep_curls', 'Bicep Curls')], max_length=20),
        ),
    ]
