# Generated by Django 5.0.1 on 2024-01-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_alter_workout_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='workouts',
            field=models.ManyToManyField(related_name='routines', to='customization.workout'),
        ),
    ]
