# Generated by Django 5.0.1 on 2024-01-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_routine_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='routine',
        ),
    ]
