# Generated by Django 5.0.1 on 2024-01-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsettings',
            name='exercise_name',
            field=models.CharField(default='Default Exercise Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutsettings',
            name='rep_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutsettings',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
