# Generated by Django 5.0.1 on 2024-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicep_curls', '0002_delete_workoutsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_count', models.IntegerField()),
                ('time_limit', models.IntegerField()),
            ],
        ),
    ]
