# Generated by Django 5.0.1 on 2024-01-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicep_curls', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutSettings',
        ),
    ]
